// Generated by gencpp from file pickup_2020/PR_control.msg
// DO NOT EDIT!


#ifndef PICKUP_2020_MESSAGE_PR_CONTROL_H
#define PICKUP_2020_MESSAGE_PR_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pickup_2020
{
template <class ContainerAllocator>
struct PR_control_
{
  typedef PR_control_<ContainerAllocator> Type;

  PR_control_()
    : pick_slide(0)
    , pick_grasp(0)
    , pick_turn(0)
    , pick_lift(0)
    , kick_roll(0)
    , Kick_fire(0)
    , pass_tee(0)  {
    }
  PR_control_(const ContainerAllocator& _alloc)
    : pick_slide(0)
    , pick_grasp(0)
    , pick_turn(0)
    , pick_lift(0)
    , kick_roll(0)
    , Kick_fire(0)
    , pass_tee(0)  {
  (void)_alloc;
    }



   typedef int32_t _pick_slide_type;
  _pick_slide_type pick_slide;

   typedef int32_t _pick_grasp_type;
  _pick_grasp_type pick_grasp;

   typedef int32_t _pick_turn_type;
  _pick_turn_type pick_turn;

   typedef int32_t _pick_lift_type;
  _pick_lift_type pick_lift;

   typedef int32_t _kick_roll_type;
  _kick_roll_type kick_roll;

   typedef int32_t _Kick_fire_type;
  _Kick_fire_type Kick_fire;

   typedef int32_t _pass_tee_type;
  _pass_tee_type pass_tee;





  typedef boost::shared_ptr< ::pickup_2020::PR_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pickup_2020::PR_control_<ContainerAllocator> const> ConstPtr;

}; // struct PR_control_

typedef ::pickup_2020::PR_control_<std::allocator<void> > PR_control;

typedef boost::shared_ptr< ::pickup_2020::PR_control > PR_controlPtr;
typedef boost::shared_ptr< ::pickup_2020::PR_control const> PR_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pickup_2020::PR_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pickup_2020::PR_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pickup_2020

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pickup_2020': ['/home/akei/catkin_ws/src/pickup_2020/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pickup_2020::PR_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pickup_2020::PR_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pickup_2020::PR_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pickup_2020::PR_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pickup_2020::PR_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pickup_2020::PR_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pickup_2020::PR_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "145426011257f665260f74de824eb711";
  }

  static const char* value(const ::pickup_2020::PR_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x145426011257f665ULL;
  static const uint64_t static_value2 = 0x260f74de824eb711ULL;
};

template<class ContainerAllocator>
struct DataType< ::pickup_2020::PR_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pickup_2020/PR_control";
  }

  static const char* value(const ::pickup_2020::PR_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pickup_2020::PR_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pick_slide\n"
"int32 pick_grasp\n"
"int32 pick_turn\n"
"int32 pick_lift\n"
"int32 kick_roll\n"
"int32 Kick_fire\n"
"int32 pass_tee\n"
;
  }

  static const char* value(const ::pickup_2020::PR_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pickup_2020::PR_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pick_slide);
      stream.next(m.pick_grasp);
      stream.next(m.pick_turn);
      stream.next(m.pick_lift);
      stream.next(m.kick_roll);
      stream.next(m.Kick_fire);
      stream.next(m.pass_tee);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PR_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pickup_2020::PR_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pickup_2020::PR_control_<ContainerAllocator>& v)
  {
    s << indent << "pick_slide: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pick_slide);
    s << indent << "pick_grasp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pick_grasp);
    s << indent << "pick_turn: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pick_turn);
    s << indent << "pick_lift: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pick_lift);
    s << indent << "kick_roll: ";
    Printer<int32_t>::stream(s, indent + "  ", v.kick_roll);
    s << indent << "Kick_fire: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Kick_fire);
    s << indent << "pass_tee: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pass_tee);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICKUP_2020_MESSAGE_PR_CONTROL_H
